# 2022년 3월의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품iD, 유저 ID, 판매량 출력
(SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE "2022-03%")
 
 UNION
 
(SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE "2022-03%")

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
