# 상품코드 별 매출액(판매가 * 판매량) 합계를 출력하는 SQL문을 작성해주세요. 
# 결과는 매출액을 기준으로 내림차순 정렬해주시고 매출액이 같다면 상품코드를 기준으로 오름차순 정렬
SELECT PRODUCT_CODE, (PRICE * SALES_AMOUNT) as SALES
FROM PRODUCT p 
JOIN (SELECT PRODUCT_ID, sum(SALES_AMOUNT) as SALES_AMOUNT FROM OFFLINE_SALE GROUP BY PRODUCT_ID) as o 
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;